/* Thư viện khai cuộc — mỗi nước: m=[cột đi, hàng đi, cột đến, hàng đến], a = chú giải */
"use strict";
var OPENINGS = [
{
  id: "phao-dau-bpm",
  name: "Pháo Đầu vs Bình Phong Mã (Hiện đại)",
  cn: "中炮对屏风马",
  side: "do", level: "Cơ bản",
  desc: "Trận đấu phổ biến nhất trong cờ Tướng hiện đại. Đỏ dùng Pháo đầu tấn công trung lộ, Đen dựng hai Mã như bức bình phong che Tốt đầu, phòng thủ chắc chắn rồi phản công.",
  idea: "Đỏ: chiếm trung lộ, ra Xe nhanh gây sức ép cánh trái Đen. Đen: giữ vững trung lộ bằng hai Mã, đẩy Tốt 7 mở đường Mã, dùng Pháo 9 đuổi Xe giành lại nhịp.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu — chiếm trung lộ, nhắm thẳng Tốt đầu và Tướng Đen. Nước khai cuộc tấn công kinh điển nhất." },
    { m: [7,0,6,2], a: "Mã nhảy lên che Tốt đầu — nước đầu tiên của hệ thống Bình Phong Mã." },
    { m: [7,9,6,7], a: "Lên Mã bảo vệ Pháo đầu và chuẩn bị ra Xe." },
    { m: [8,0,7,0], a: "Ra Xe đối đầu với Xe Đỏ sắp xuất hiện — tranh tiên trên cột 8." },
    { m: [8,9,7,9], a: "Xe trực — ra Xe nhanh nhất, đối mặt Xe Đen trên cùng cột." },
    { m: [1,0,2,2], a: "Mã thứ hai nhảy lên, hoàn thành thế Bình Phong Mã: hai Mã cùng bảo vệ Tốt đầu." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7 mở đường cho Mã trái sau này — nước chờ linh hoạt." },
    { m: [6,3,6,4], a: "Đen cũng đẩy Tốt 7 mở đường Mã, đồng thời kiểm soát điểm qua hà của Mã Đỏ." },
    { m: [7,9,7,3], a: "Xe qua hà — chiếm tuyến tấn công, đè lên đầu Mã Đen, gây sức ép lớn." },
    { m: [7,2,8,2], a: "Bình Pháo ra biên, nhường đường và chuẩn bị đuổi Xe Đỏ — kế hoạch phản kích chủ đạo." },
    { m: [7,3,6,3], a: "Xe ép sát cột 3, đè đầu Mã và dòm Tốt 7 của Đen." },
    { m: [8,2,8,1], a: "Pháo lùi một bước — chuẩn bị bình sang cột 7 đuổi Xe, đòn phản công đặc trưng." },
    { m: [1,9,2,7], a: "Đỏ bình tĩnh lên nốt Mã trái, hoàn thiện phát triển." },
    { m: [3,0,4,1], a: "Lên Sĩ củng cố trung lộ — Đen ưu tiên an toàn trước khi phản công." },
    { m: [4,6,4,5], a: "Đẩy Tốt đầu — mở đường tấn công trung lộ, phối hợp với Pháo đầu." },
    { m: [8,1,6,1], a: "Pháo bình 7 — mượn Mã làm ngòi tấn công Xe Đỏ, buộc Xe phải chạy." },
    { m: [6,3,5,3], a: "Xe tránh sang cột 4, vẫn giữ vị trí tấn công qua hà." },
    { m: [2,0,4,2], a: "Phi Tượng lên che trung lộ, liên kết phòng thủ." },
    { m: [2,7,3,5], a: "Mã nhảy lên hà — Mã bàn hà rất mạnh, phối hợp Xe Pháo dọa đánh vào cánh Đen." },
    { m: [7,0,7,5], a: "Xe Đen tiến sát hà đáp trả — hai bên hoàn thành khai cuộc, thế trận cân bằng và giàu biến hóa." }
  ]
},
{
  id: "qua-ha-xa",
  name: "Trung Pháo Quá Hà Xa vs Bình Phong Mã",
  cn: "中炮过河车对屏风马",
  side: "do", level: "Trung cấp",
  desc: "Biến quyết liệt của Pháo đầu: Đỏ cho Xe qua hà sớm ngay nước thứ 4 để đè ép quân Đen trước khi Đen kịp triển khai đầy đủ.",
  idea: "Đỏ: Xe qua hà sớm chiếm không gian, kết hợp đẩy Tốt đầu phá trung lộ. Đen: dùng Pháo biên đuổi Xe, đẩy Tốt 7 phản kích giành lại quyền chủ động.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu chiếm trung lộ." },
    { m: [7,0,6,2], a: "Đen lên Mã theo hệ thống Bình Phong Mã." },
    { m: [7,9,6,7], a: "Lên Mã giữ Pháo, chuẩn bị ra Xe." },
    { m: [8,0,7,0], a: "Đen ra Xe tranh cột." },
    { m: [8,9,7,9], a: "Ra Xe trực." },
    { m: [1,0,2,2], a: "Hoàn thành thế Bình Phong Mã." },
    { m: [7,9,7,3], a: "Xe qua hà ngay! Đặc trưng của trận này — chiếm tuyến, uy hiếp cả hai cánh Đen." },
    { m: [6,3,6,4], a: "Đẩy Tốt 7 — vừa mở đường Mã vừa chuẩn bị đuổi Xe Đỏ." },
    { m: [1,9,2,7], a: "Lên nốt Mã trái, phát triển cân đối." },
    { m: [7,2,8,2], a: "Pháo bình ra biên, khởi động kế hoạch đuổi Xe." },
    { m: [7,3,6,3], a: "Xe áp sát cột 3 đè đầu Mã Đen." },
    { m: [8,2,8,1], a: "Pháo thoái một — sắp bình sang cột 7 tấn công Xe." },
    { m: [4,6,4,5], a: "Đẩy Tốt đầu lần một — bắt đầu kế hoạch phá trung lộ." },
    { m: [3,0,4,1], a: "Lên Sĩ giữ vững trung tâm." },
    { m: [4,5,4,4], a: "Đẩy Tốt đầu lần hai — Tốt qua hà, sức ép trung lộ tăng mạnh." },
    { m: [8,1,6,1], a: "Pháo bình 7, mượn ngòi Mã bắt Xe — Đỏ buộc phải di chuyển Xe." },
    { m: [6,3,5,3], a: "Xe né sang cột 4, giữ thế qua hà." },
    { m: [6,4,6,5], a: "Tốt 7 qua hà phản kích — Đen đổi lại không gian ở cánh phải Đỏ." },
    { m: [5,3,5,1], a: "Xe thọc sâu xuống tuyến hai dọa quấy phá hậu phương Đen." },
    { m: [1,2,1,6], a: "Pháo 2 qua hà đáp trả — đôi bên đối công gay gắt, ai chính xác hơn sẽ thắng." }
  ]
},
{
  id: "ngu-that-phao",
  name: "Ngũ Thất Pháo vs Bình Phong Mã",
  cn: "五七炮对屏风马",
  side: "do", level: "Trung cấp",
  desc: "Đỏ đặt hai Pháo ở lộ 5 và lộ 7 (Ngũ Thất Pháo), tạo thế tấn công hai cánh phối hợp — vừa ép trung lộ vừa nhắm vào Mã 3 của Đen.",
  idea: "Đỏ: Pháo 7 kiềm chế Mã 3 Đen, Mã biên + Xe trái tấn công cánh. Đen: củng cố trung lộ, dùng Pháo tuần hà linh hoạt phòng ngự phản công.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu — mở màn quen thuộc." },
    { m: [7,0,6,2], a: "Đen lên Mã cánh trái." },
    { m: [7,9,6,7], a: "Lên Mã phải." },
    { m: [8,0,7,0], a: "Ra Xe cột 8." },
    { m: [8,9,7,9], a: "Xe trực đối đầu." },
    { m: [1,0,2,2], a: "Hoàn thành Bình Phong Mã." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7 mở đường Mã trái." },
    { m: [6,3,6,4], a: "Đen đẩy Tốt 7 đáp lại." },
    { m: [1,7,2,7], a: "Pháo bình 7 — hình thành Ngũ Thất Pháo, ngắm thẳng Mã 3 và Tượng Đen." },
    { m: [2,0,4,2], a: "Phi Tượng che trung lộ, hóa giải bớt sức ép của Pháo đầu." },
    { m: [1,9,0,7], a: "Mã nhảy ra biên — nhường đường cho Xe trái xuất trận theo cột 8." },
    { m: [3,0,4,1], a: "Lên Sĩ, thế thủ Đen thêm vững." },
    { m: [0,9,1,9], a: "Xe trái ra cột 8 — cả hai Xe Đỏ đều đã vào cuộc." },
    { m: [7,2,7,4], a: "Pháo tuần hà — vừa giữ Tốt vừa sẵn sàng dời ngang tạo ngòi chiến thuật." },
    { m: [1,9,1,3], a: "Xe tiến sâu xuống tuyến Tốt, quấy rối hậu phương Đen." },
    { m: [1,2,0,2], a: "Pháo né sang biên tránh Xe — thế trận Ngũ Thất Pháo giằng co từng nước, hai cánh đều nóng bỏng." }
  ]
},
{
  id: "ngu-luc-phao",
  name: "Ngũ Lục Pháo vs Bình Phong Mã",
  cn: "五六炮对屏风马",
  side: "do", level: "Trung cấp",
  desc: "Đỏ đặt Pháo ở lộ 5 và lộ 6. So với Ngũ Thất Pháo, thế trận này thiên về vững chắc: Pháo 6 vừa thủ vừa hỗ trợ tấn công trung lộ và cánh phải.",
  idea: "Đỏ: cấu trúc cân bằng công thủ, Xe Mã phối hợp ép dần. Đen: phi Tượng, lên Sĩ giữ chắc rồi tìm cơ hội phản kích ở cánh.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu chiếm trung." },
    { m: [7,0,6,2], a: "Mã che Tốt đầu." },
    { m: [7,9,6,7], a: "Lên Mã phải." },
    { m: [8,0,7,0], a: "Ra Xe." },
    { m: [8,9,7,9], a: "Xe trực." },
    { m: [1,0,2,2], a: "Bình Phong Mã hoàn chỉnh." },
    { m: [6,6,6,5], a: "Đẩy Tốt 3 — mở đường Mã phải, hướng phát triển đặc trưng của Ngũ Lục Pháo." },
    { m: [2,3,2,4], a: "Đen đẩy Tốt 3 đáp lại, mở đường Mã 3." },
    { m: [1,7,3,7], a: "Pháo bình 6 — hình thành Ngũ Lục Pháo, củng cố cánh phải và trợ chiến trung lộ." },
    { m: [6,0,4,2], a: "Phi Tượng 7 che trung lộ." },
    { m: [1,9,2,7], a: "Lên Mã trái, đội hình Đỏ liền lạc." },
    { m: [5,0,4,1], a: "Lên Sĩ 6 — bộ khung Sĩ Tượng của Đen hoàn chỉnh." },
    { m: [0,9,1,9], a: "Xe trái ra cột 8, hai Xe thông suốt." },
    { m: [6,3,6,4], a: "Đen đẩy nốt Tốt 7, hai Mã đều có đường tiến." },
    { m: [1,9,1,5], a: "Xe tuần hà — kiểm soát tuyến sông, sẵn sàng dời sang cánh gây sức ép." },
    { m: [7,2,7,4], a: "Pháo Đen cũng tuần hà đối trọng — thế trận giằng co chiến lược." }
  ]
},
{
  id: "thuan-phao",
  name: "Thuận Pháo (Trực Xa vs Hoành Xa)",
  cn: "顺炮直车对横车",
  side: "do", level: "Cơ bản",
  desc: "Hai bên cùng vào Pháo đầu về cùng một phía (thuận chiều). Trận đấu cổ điển từ thời Quất Trung Bí, thiên về đối công nhanh, tốc độ ra quân quyết định tất cả.",
  idea: "Đỏ: ra Xe trực nhanh chiếm cột mở. Đen: dùng Xe hoành linh hoạt chuyển cánh. Cả hai bỏ ngỏ trung lộ để đua tốc độ tấn công.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [7,2,4,2], a: "Đen cũng vào Pháo đầu cùng phía — hình thành trận Thuận Pháo." },
    { m: [7,9,6,7], a: "Lên Mã giữ Pháo." },
    { m: [7,0,6,2], a: "Đen lên Mã tương ứng." },
    { m: [8,9,7,9], a: "Xe trực — ra Xe nhanh nhất có thể." },
    { m: [8,0,8,1], a: "Xe hoành! Đen đưa Xe lên một bước để dời ngang sang cánh — linh hồn của thế trận này." },
    { m: [1,9,2,7], a: "Đỏ lên nốt Mã trái." },
    { m: [8,1,3,1], a: "Xe bình 4 — Xe hoành chiếm lộ Sĩ, sẵn sàng tấn công cánh phải Đỏ." },
    { m: [6,6,6,5], a: "Đẩy Tốt 3 mở đường Mã phải." },
    { m: [1,0,2,2], a: "Đen lên nốt Mã, hai bên phát triển thần tốc." },
    { m: [7,9,7,3], a: "Xe qua hà tạo sức ép — Đỏ tận dụng lợi thế ra Xe trước." },
    { m: [2,3,2,4], a: "Đen đẩy Tốt 3 mở đường phản công." },
    { m: [7,3,6,3], a: "Xe ăn Tốt 7! Đỏ thu lợi nhỏ nhưng phải cẩn thận vì Xe hơi xa nhà." },
    { m: [3,1,3,4], a: "Xe Đen chiếm tuyến hà, kiểm soát không gian đáp trả." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7 mở đường Mã trái, củng cố thế trận." },
    { m: [0,0,1,0], a: "Xe phải của Đen cũng ra trận — đôi bên dàn quân xong, cuộc chiến bắt đầu." }
  ]
},
{
  id: "nghich-phao",
  name: "Nghịch Pháo (Liệt Pháo)",
  cn: "列炮",
  side: "den", level: "Trung cấp",
  desc: "Đen vào Pháo đầu ngược phía với Đỏ. Hai khẩu Pháo giữa bàn chĩa vào nhau ở hai cánh khác nhau tạo thế đối công cực kỳ sắc bén.",
  idea: "Cả hai bên đều tấn công trung lộ từ hai hướng ngược nhau. Ai chậm một nhịp trong việc ra Xe và phối hợp quân sẽ bị đòn trước.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [1,2,4,2], a: "Đen vào Pháo đầu phía ngược lại — hình thành trận Nghịch Pháo (Liệt Pháo)." },
    { m: [7,9,6,7], a: "Lên Mã giữ trung." },
    { m: [1,0,2,2], a: "Đen lên Mã phía Pháo vừa dời đi." },
    { m: [8,9,7,9], a: "Ra Xe trực." },
    { m: [0,0,1,0], a: "Đen ra Xe cột 2 — đối xứng gương với Đỏ." },
    { m: [1,9,2,7], a: "Lên nốt Mã trái." },
    { m: [7,0,6,2], a: "Đen cũng hoàn thiện cặp Mã." },
    { m: [7,9,7,3], a: "Xe qua hà trước — lợi thế đi tiên bắt đầu phát huy." },
    { m: [1,0,1,6], a: "Xe Đen cũng lập tức qua hà — hai Xe cùng xâm nhập, thế cờ căng như dây đàn." },
    { m: [7,3,6,3], a: "Xe ăn Tốt 7, phá cấu trúc Tốt của Đen." },
    { m: [1,6,2,6], a: "Xe Đen ăn lại Tốt 7 của Đỏ — ăn miếng trả miếng!" },
    { m: [0,9,0,8], a: "Xe trái Đỏ lên hoành, chuẩn bị dời sang trợ chiến." },
    { m: [8,0,8,1], a: "Xe trái Đen cũng hoành theo — đối xứng đến kỳ lạ." },
    { m: [0,8,5,8], a: "Xe bình 4 chiếm lộ Sĩ — sẵn sàng đánh thẳng vào yếu điểm cung Tướng Đen." },
    { m: [8,1,3,1], a: "Đen đáp lại y hệt. Thế trận đối công thuần túy: bên nào ra đòn chính xác hơn sẽ định đoạt ván cờ." }
  ]
},
{
  id: "phan-cung-ma",
  name: "Pháo Đầu vs Phản Cung Mã",
  cn: "中炮对反宫马",
  side: "den", level: "Nâng cao",
  desc: "Đen kẹp một khẩu Pháo giữa hai Mã (Pháo sĩ giác) tạo thế Phản Cung Mã — hệ thống phòng thủ số một của kỳ vương Hồ Vinh Hoa, mềm dẻo và đầy phản đòn.",
  idea: "Đen: Pháo 6 khống chế điểm nhảy Mã của Đỏ, thế thủ co giãn. Đỏ: tấn công vào điểm yếu tạm thời — Mã 8 chậm phát triển và cánh trái Đen hơi mỏng.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [1,0,2,2], a: "Đen lên Mã phải trước." },
    { m: [7,9,6,7], a: "Lên Mã." },
    { m: [7,2,5,2], a: "Pháo bình 6 vào góc Sĩ — nước cờ định hình Phản Cung Mã, khống chế lộ 6." },
    { m: [8,9,7,9], a: "Ra Xe trực." },
    { m: [7,0,6,2], a: "Đen lên nốt Mã trái, hai Mã kẹp Pháo — thế Phản Cung Mã hoàn chỉnh." },
    { m: [6,6,6,5], a: "Đẩy Tốt 3 — tấn công đúng vào cánh Mã vừa lên của Đen." },
    { m: [2,3,2,4], a: "Đen đẩy Tốt 3 giành không gian cho Mã phải." },
    { m: [1,9,0,7], a: "Mã biên — tránh để Pháo 6 của Đen bắt chết điểm nhảy Mã 7." },
    { m: [2,0,4,2], a: "Phi Tượng che trung lộ, thế thủ nhiều tầng." },
    { m: [0,9,1,9], a: "Xe trái ra cột 8." },
    { m: [0,0,1,0], a: "Đen ra Xe cột 2 đối trọng." },
    { m: [7,9,7,5], a: "Xe tiến chiếm tuyến, dòm ngó Tốt cánh Đen." },
    { m: [3,0,4,1], a: "Lên Sĩ — Đen bình tĩnh củng cố, chờ Đỏ sơ hở để tung phản đòn đặc trưng của Phản Cung Mã." },
    { m: [2,6,2,5], a: "Đỏ đẩy Tốt 7 giành thêm không gian." },
    { m: [6,3,6,4], a: "Đen đáp Tốt 7 — khai cuộc hoàn tất, trung cuộc sẽ xoay quanh cuộc chiến giành lộ 6." }
  ]
},
{
  id: "don-de-ma",
  name: "Pháo Đầu vs Đơn Đề Mã",
  cn: "中炮对单提马",
  side: "den", level: "Trung cấp",
  desc: "Đen phòng thủ bằng một Mã chính giữa và một Mã biên (đơn đề). Thế trận cổ điển, nhường trung lộ để đổi lấy cấu trúc linh hoạt và phản công cánh.",
  idea: "Đen: Mã biên giải phóng cột cho Xe, Pháo 7 phòng ngự chờ thời. Đỏ: tận dụng trung lộ thoáng để tấn công nhanh vào Tốt đầu.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [1,0,2,2], a: "Đen lên Mã phải." },
    { m: [7,9,6,7], a: "Lên Mã." },
    { m: [7,0,8,2], a: "Mã nhảy ra biên — nước đặc trưng của Đơn Đề Mã, nhường cột 8 cho Xe." },
    { m: [8,9,7,9], a: "Ra Xe trực." },
    { m: [7,2,6,2], a: "Pháo bình 7 trấn giữ, bảo vệ điểm yếu trước Xe Đỏ." },
    { m: [1,9,2,7], a: "Lên nốt Mã trái." },
    { m: [8,0,7,0], a: "Đen ra Xe đối đầu — nhờ Mã biên, Xe ra rất thông thoáng." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7 mở đường Mã." },
    { m: [2,0,4,2], a: "Phi Tượng giữ trung lộ." },
    { m: [0,9,0,8], a: "Xe trái hoành — chuẩn bị dời sang lộ giữa hoặc lộ 6 tăng viện." },
    { m: [3,0,4,1], a: "Lên Sĩ hoàn chỉnh thế thủ." },
    { m: [0,8,3,8], a: "Xe bình 6 chiếm lộ Sĩ — hướng tấn công nguy hiểm nhất khi Đen thủ Đơn Đề Mã." },
    { m: [0,0,1,0], a: "Xe phải Đen ra cột 2, sẵn sàng đổi quân giảm sức ép." },
    { m: [4,6,4,5], a: "Đẩy Tốt đầu — khoét vào trung lộ, điểm mạnh của Đỏ trong trận này." },
    { m: [8,3,8,4], a: "Đen đẩy Tốt biên khởi động Mã biên — nguồn phản công tiềm tàng của Đơn Đề Mã." }
  ]
},
{
  id: "uyen-uong-phao",
  name: "Pháo Đầu vs Uyên Ương Pháo",
  cn: "中炮对鸳鸯炮",
  side: "den", level: "Nâng cao",
  desc: "Đen dồn hai khẩu Pháo về cùng một cột như đôi uyên ương quấn quýt — thế trận lạ, giăng bẫy Xe Đỏ và phản kích bất ngờ.",
  idea: "Đen: nhử Xe Đỏ vào sâu rồi dùng cặp Pháo cùng Xe hoành vây bắt. Đỏ: phát triển thận trọng, không tham ăn để tránh sập bẫy.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [1,0,2,2], a: "Đen lên Mã phải." },
    { m: [7,9,6,7], a: "Lên Mã." },
    { m: [8,0,8,1], a: "Xe hoành — bước chuẩn bị đầu tiên của Uyên Ương Pháo." },
    { m: [8,9,7,9], a: "Ra Xe trực." },
    { m: [7,0,8,2], a: "Mã nhảy biên bảo vệ góc trái, đồng thời dọn chỗ cho kế hoạch Pháo trùng sắp tới." },
    { m: [1,9,2,7], a: "Đỏ cứ bình tĩnh phát triển." },
    { m: [7,2,7,1], a: "Pháo thoái một! Nước cờ lạ mắt — chuẩn bị kéo Pháo về cùng cột với khẩu kia." },
    { m: [7,9,7,3], a: "Xe qua hà chiếm thế, thăm dò trận địa lạ của Đen." },
    { m: [7,1,1,1], a: "Pháo bình về cột 2 — hai Pháo Đen chồng lên nhau: thế Uyên Ương Pháo ra đời!" },
    { m: [2,6,2,5], a: "Đẩy Tốt 7, mở đường Mã và cho Xe thêm lối thoát." },
    { m: [8,1,3,1], a: "Xe hoành dời sang lộ 4 — cánh quân thứ hai của kế hoạch vây ép." },
    { m: [5,9,4,8], a: "Đỏ lên Sĩ chắc chắn, không cho Đen cơ hội đánh úp trung lộ." },
    { m: [6,0,4,2], a: "Phi Tượng 7 củng cố phòng tuyến." },
    { m: [4,6,4,5], a: "Đẩy Tốt đầu tăng sức ép trung lộ." },
    { m: [5,0,4,1], a: "Lên Sĩ 6 hoàn thiện phòng tuyến — trận Uyên Ương Pháo dàn xong, trung cuộc sẽ đầy cạm bẫy." }
  ]
},
{
  id: "quy-boi-phao",
  name: "Pháo Đầu vs Quy Bối Pháo",
  cn: "中炮对龟背炮",
  side: "den", level: "Nâng cao",
  desc: "Đen rút Pháo về sát lưng Tướng như mai rùa (quy bối) rồi chuyển sang cột 8 lập thế Pháo chồng đánh úp Xe Đỏ — khai cuộc kỳ hình đầy chất phục kích.",
  idea: "Đen: hy sinh tốc độ đổi lấy đòn đánh úp cột 8, khiến Xe Đỏ không dám ra tự nhiên. Đỏ: đổi hướng ra Xe trái và dùng Xe hoành để hóa giải.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [1,0,2,2], a: "Đen lên Mã phải." },
    { m: [7,9,6,7], a: "Lên Mã." },
    { m: [1,2,1,1], a: "Pháo thoái một — bước đầu của Quy Bối Pháo, lùi về sát lưng như mai rùa." },
    { m: [1,9,2,7], a: "Đỏ lên nốt Mã trái, chưa vội ra Xe phải." },
    { m: [7,0,6,2], a: "Lên Mã trái trước — dọn sẵn đường cho khẩu Pháo kéo sang và Xe ra chống lưng." },
    { m: [0,9,1,9], a: "Đỏ ra Xe trái, thăm dò ý đồ kỳ lạ của Đen." },
    { m: [1,1,7,1], a: "Pháo bình 8! Hai Pháo Đen chồng cột 8 — Xe phải của Đỏ mà ra cột này sẽ bị đánh úp ngay." },
    { m: [8,9,8,8], a: "Xe phải lên hoành — cách an toàn duy nhất để kích hoạt Xe này." },
    { m: [8,0,7,0], a: "Xe ra chống lưng cặp Pháo — khối Xe-Pháo-Pháo cột 8 là trái tim của Quy Bối Pháo." },
    { m: [8,8,5,8], a: "Xe hoành bình về lộ 4, chiếm đường tiến công cạnh cung Tướng Đen." },
    { m: [6,0,4,2], a: "Đen phi Tượng củng cố trung lộ." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7 mở đường cho Mã trái nhảy lên hà." },
    { m: [5,0,4,1], a: "Lên Sĩ giữ cung Tướng." },
    { m: [2,7,3,5], a: "Mã nhảy lên hà chiếm thế — Đỏ hoàn tất phát triển với thế trận thoáng hơn." },
    { m: [6,3,6,4], a: "Đen đẩy Tốt 7 mở đường Mã trái — Quy Bối Pháo giữ nguyên sức ép ngầm trên cột 8, chờ thời cơ phản công." }
  ]
},
{
  id: "phi-tuong-cuc",
  name: "Phi Tượng Cục",
  cn: "飞相局",
  side: "do", level: "Cơ bản",
  desc: "Đỏ mở màn bằng nước phi Tượng che Tốt đầu — khai cuộc thiên về thế trận, mềm mại mà sâu sắc, được giới cao thủ hiện đại rất ưa chuộng.",
  idea: "Đỏ: nhường tiên thủ trước, giữ cấu trúc hoàn hảo rồi phản công khi Đen quá đà. Đen: thường vào Pháo đầu ngay để trừng phạt sự chậm rãi.",
  moves: [
    { m: [6,9,4,7], a: "Phi Tượng — che Tốt đầu, nước mở màn hiền hòa nhưng ẩn chứa nội lực thế trận." },
    { m: [7,2,4,2], a: "Đen lập tức vào Pháo đầu — cách đối phó tích cực nhất với Phi Tượng Cục." },
    { m: [1,9,2,7], a: "Lên Mã trái bảo vệ trung lộ." },
    { m: [7,0,6,2], a: "Đen lên Mã giữ Pháo." },
    { m: [0,9,1,9], a: "Ra Xe trái sớm — cột 8 là bàn đạp chính của Đỏ trong trận này." },
    { m: [8,0,7,0], a: "Đen ra Xe đối đầu." },
    { m: [7,9,6,7], a: "Lên nốt Mã phải, đội hình Đỏ cực kỳ chắc chắn." },
    { m: [1,0,2,2], a: "Đen hoàn thiện cặp Mã." },
    { m: [6,6,6,5], a: "Đẩy Tốt 3 giành không gian cánh phải." },
    { m: [0,0,0,1], a: "Xe phải Đen lên hoành, tìm đường sang trung lộ." },
    { m: [5,9,4,8], a: "Lên Sĩ — bộ khung Sĩ Tượng liền lạc, đặc sản của Phi Tượng Cục." },
    { m: [0,1,5,1], a: "Xe hoành chiếm lộ 6, dòm vào cung Tướng Đỏ." },
    { m: [7,7,7,5], a: "Pháo tuần hà — phòng tuyến sông nước chắc chắn, sẵn sàng dời ngang làm ngòi." },
    { m: [6,3,6,4], a: "Đen đẩy Tốt 7 hoạt động Mã." },
    { m: [8,9,7,9], a: "Xe phải ra nốt — Đỏ hoàn thành khai cuộc với thế trận không một kẽ hở." },
    { m: [3,0,4,1], a: "Đen lên Sĩ. Trận Phi Tượng đi vào trung cuộc giằng co — đúng phong cách 'lấy nhu thắng cương'." }
  ]
},
{
  id: "tien-nhan-chi-lo",
  name: "Tiên Nhân Chỉ Lộ (Đối Binh Cục)",
  cn: "仙人指路对卒底炮",
  side: "do", level: "Cơ bản",
  desc: "'Tiên ông chỉ đường' — Đỏ đẩy Tốt 3 thăm dò, giấu kín ý đồ. Đen đáp Tốt 3 tạo Đối Binh Cục. Khai cuộc mềm dẻo, dễ chuyển hóa về nhiều trận hình khác.",
  idea: "Đỏ: nước Tốt thăm dò giữ mọi lựa chọn mở, sau đó chuyển về Pháo đầu. Đen: đối Tốt giành cân bằng không gian ngay từ đầu.",
  moves: [
    { m: [6,6,6,5], a: "Tiên nhân chỉ lộ — đẩy Tốt 3 mở đường Mã, nước thăm dò kín đáo khiến Đen khó đoán ý đồ." },
    { m: [2,3,2,4], a: "Đen đối Tốt 3 — hình thành Đối Binh Cục, cân bằng không gian tức thì." },
    { m: [7,7,4,7], a: "Chuyển về Pháo đầu — lộ rõ ý đồ: nước Tốt trước đó đã chuẩn bị sẵn đường Mã." },
    { m: [7,0,6,2], a: "Đen lên Mã che Tốt đầu." },
    { m: [7,9,6,7], a: "Lên Mã phải." },
    { m: [8,0,7,0], a: "Đen ra Xe." },
    { m: [8,9,7,9], a: "Ra Xe trực đối đầu." },
    { m: [1,0,2,2], a: "Đen hoàn thành Bình Phong Mã." },
    { m: [1,9,0,7], a: "Mã biên — giữ đường Xe trái thông suốt." },
    { m: [2,0,4,2], a: "Phi Tượng củng cố trung lộ." },
    { m: [1,7,2,7], a: "Pháo bình 7 dòm Mã 3 và Tượng Đen — tận dụng cột Tốt đã mở." },
    { m: [0,0,1,0], a: "Xe phải Đen ra cột 2." },
    { m: [0,9,1,9], a: "Xe trái Đỏ ra cột 8 — hai bên dàn trận cân não." },
    { m: [1,2,1,6], a: "Pháo 2 qua hà — Đen chủ động khiêu chiến, đặt Pháo vào lòng đất địch." },
    { m: [4,6,4,5], a: "Đỏ đẩy Tốt đầu phản ứng trung lộ." },
    { m: [3,0,4,1], a: "Đen lên Sĩ. Đối Binh Cục khép lại giai đoạn khai cuộc với thế trận cân bằng, giàu chiến lược." }
  ]
},
{
  id: "khoi-ma-cuc",
  name: "Khởi Mã Cục",
  cn: "起马局",
  side: "do", level: "Cơ bản",
  desc: "Đỏ mở màn bằng nước lên Mã — linh hoạt, tránh lý thuyết Pháo đầu đồ sộ. Mã lên trước giữ trung lộ và chờ xem cách bố trận của Đen rồi mới định hình.",
  idea: "Đỏ: phát triển tự nhiên, giữ thế cân bằng rồi tùy cơ ứng biến. Đen: đẩy Tốt 7 giành không gian là cách đáp phổ biến nhất.",
  moves: [
    { m: [7,9,6,7], a: "Khởi Mã — lên Mã trước, nước mở màn linh hoạt bậc nhất: chưa lộ chút ý đồ nào." },
    { m: [6,3,6,4], a: "Đen đẩy Tốt 7 — đáp án tích cực nhất, giành không gian và kiềm chế Mã Đỏ." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7 mở đường Mã trái, cân bằng cấu trúc." },
    { m: [7,0,6,2], a: "Đen lên Mã." },
    { m: [1,9,2,7], a: "Lên nốt Mã trái — hai Mã Đỏ như đôi cánh én." },
    { m: [8,0,8,1], a: "Đen dùng Xe hoành, chuẩn bị dời sang lộ 4 hoạt động." },
    { m: [0,9,0,8], a: "Đỏ cũng Xe hoành đáp lại — trận đấu của những nước cờ mềm." },
    { m: [8,1,3,1], a: "Xe Đen bình 4 chiếm lộ Sĩ." },
    { m: [0,8,5,8], a: "Xe Đỏ bình 4 — tránh đối mặt trực tiếp, chiếm lộ 4 cạnh cung Tướng." },
    { m: [1,0,2,2], a: "Đen lên nốt Mã." },
    { m: [7,7,8,7], a: "Pháo bình biên — dọn cột cho Xe sau, đồng thời ngắm tuyến biên thông thoáng." },
    { m: [7,2,8,2], a: "Đen cũng bình Pháo biên đối xứng." },
    { m: [5,8,5,5], a: "Xe tiến chiếm hà — kiểm soát tuyến sông trước." },
    { m: [6,0,4,2], a: "Đen phi Tượng vững vàng. Khởi Mã Cục cho thấy: không cần Pháo đầu vẫn có thế trận đầy sức sống." }
  ]
},
{
  id: "qua-cung-phao",
  name: "Quá Cung Pháo",
  cn: "过宫炮",
  side: "do", level: "Trung cấp",
  desc: "Đỏ đưa Pháo băng qua cung Tướng sang lộ 6 — dồn lực lượng về một cánh, tạo thế công thủ toàn diện bên cánh phải.",
  idea: "Đỏ: Pháo quá cung + Sĩ Tượng + Xe tạo khối vững bên cánh phải rồi đẩy quân tấn công cánh đó. Đen: phát triển nhanh cánh đối diện để cân bằng.",
  moves: [
    { m: [7,7,3,7], a: "Quá Cung Pháo — Pháo băng ngang qua cung Tướng sang lộ 6, dồn hỏa lực về một cánh." },
    { m: [7,0,6,2], a: "Đen lên Mã trái." },
    { m: [7,9,6,7], a: "Lên Mã phải." },
    { m: [8,0,7,0], a: "Đen ra Xe." },
    { m: [8,9,7,9], a: "Ra Xe trực — Xe, Mã, Pháo Đỏ quây quần bên cánh phải thành khối thép." },
    { m: [6,3,6,4], a: "Đen đẩy Tốt 7 hoạt động Mã." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7 mở đường Mã trái." },
    { m: [1,0,2,2], a: "Đen lên nốt Mã." },
    { m: [1,9,2,7], a: "Lên Mã trái — đội hình Đỏ cân đối lạ thường dù Pháo đã dồn cánh." },
    { m: [2,0,4,2], a: "Đen phi Tượng giữ trung lộ." },
    { m: [5,9,4,8], a: "Lên Sĩ 4 — hoàn thiện cấu trúc quá cung: Pháo nằm gọn sau lưng Sĩ." },
    { m: [3,0,4,1], a: "Đen cũng lên Sĩ." },
    { m: [0,9,1,9], a: "Xe trái ra cột 8, hai Xe Đỏ đều thông." },
    { m: [0,0,1,0], a: "Xe phải Đen ra cột 2 đối trọng." },
    { m: [4,6,4,5], a: "Đẩy Tốt đầu giành trung lộ." },
    { m: [7,2,7,6], a: "Pháo 8 qua hà phản kích — Đen không chịu lép, thế trận hai cánh đối xứng đầy kịch tính." }
  ]
},
{
  id: "si-giac-phao",
  name: "Sĩ Giác Pháo",
  cn: "士角炮",
  side: "do", level: "Trung cấp",
  desc: "Đỏ bình Pháo vào góc Sĩ (lộ 4) — khai cuộc kín đáo: Pháo vừa bảo vệ cung Tướng vừa sẵn sàng tung ra tuyến giữa hoặc tuyến 4 tấn công.",
  idea: "Đỏ: giữ Pháo trong nhà như mũi tên đặt sẵn trên cung, phát triển đầy đủ rồi mới bung sức. Đen: dàn trận cân bằng, không cho Pháo góc có mục tiêu.",
  moves: [
    { m: [7,7,5,7], a: "Sĩ Giác Pháo — Pháo nép vào góc Sĩ, nước mở màn trầm lặng mà đầy ẩn ý." },
    { m: [7,0,6,2], a: "Đen lên Mã trái." },
    { m: [7,9,6,7], a: "Lên Mã phải." },
    { m: [8,0,7,0], a: "Đen ra Xe." },
    { m: [8,9,7,9], a: "Ra Xe trực đối đầu." },
    { m: [1,0,2,2], a: "Đen hoàn thành cặp Mã bình phong." },
    { m: [1,9,2,7], a: "Lên nốt Mã trái." },
    { m: [6,3,6,4], a: "Đen đẩy Tốt 7." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7 đáp lại, mở đường Mã." },
    { m: [2,0,4,2], a: "Đen phi Tượng giữ trung." },
    { m: [0,9,1,9], a: "Xe trái ra cột 8." },
    { m: [0,0,1,0], a: "Xe phải Đen ra cột 2 — bốn Xe đều đã nhập cuộc." },
    { m: [3,9,4,8], a: "Lên Sĩ 6 — che chắn cho Pháo góc, khối cung Tướng kín như bưng." },
    { m: [3,0,4,1], a: "Đen lên Sĩ theo." },
    { m: [1,7,1,5], a: "Pháo 8 tuần hà — khẩu Pháo thứ hai kiểm soát tuyến sông, được Xe cột 8 chống lưng." },
    { m: [7,2,7,6], a: "Pháo Đen qua hà khiêu chiến — khai cuộc khép lại, đôi Pháo hai bên đều đã giương cung chờ bắn." }
  ]
},
{
  id: "tam-bo-ho",
  name: "Tam Bộ Hổ (bên Đen)",
  cn: "三步虎",
  side: "den", level: "Trung cấp",
  desc: "'Ba bước thành hổ' — Đen đi Mã, ra Xe, bình Pháo biên chỉ trong ba nước để Xe xuất trận cực nhanh, lập tức giành quyền phản công.",
  idea: "Đen: tốc độ trên hết — Xe thông nòng ngay nước thứ ba, Pháo biên phối hợp đuổi đánh Xe Đỏ. Đỏ: tận dụng trung lộ khi Đen dồn quân ra cánh.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [7,0,6,2], a: "Bước một: lên Mã." },
    { m: [7,9,6,7], a: "Đỏ lên Mã." },
    { m: [8,0,7,0], a: "Bước hai: ra Xe." },
    { m: [8,9,7,9], a: "Đỏ ra Xe trực." },
    { m: [7,2,8,2], a: "Bước ba: Pháo bình biên — 'tam bộ hổ' hoàn thành! Xe Đen thông nòng, hổ đã mọc cánh." },
    { m: [7,9,7,3], a: "Xe Đỏ qua hà ngay, không cho Đen kịp phát huy tốc độ." },
    { m: [1,0,2,2], a: "Đen lên nốt Mã phải." },
    { m: [1,9,2,7], a: "Đỏ lên Mã trái, phát triển đầy đủ." },
    { m: [6,3,6,4], a: "Đẩy Tốt 7 — mở đường Mã và giăng bẫy Xe Đỏ." },
    { m: [7,3,6,3], a: "Xe bình 3 dòm Tốt — nhưng cẩn thận, Xe đang vào vùng phục kích." },
    { m: [8,2,8,1], a: "Pháo thoái một — chuẩn bị bình 7 đánh Xe, đòn phản kích ruột của Tam Bộ Hổ." },
    { m: [2,6,2,5], a: "Đỏ đẩy Tốt 7 mở thêm đường rút cho Xe." },
    { m: [8,1,6,1], a: "Pháo bình 7! Mượn ngòi Mã bắt Xe — Đỏ buộc phải di dời." },
    { m: [6,3,5,3], a: "Xe né sang lộ 4 an toàn." },
    { m: [2,0,4,2], a: "Đen phi Tượng, thế trận ổn định — Tam Bộ Hổ đã hoàn thành mục tiêu: giành nhịp phản công sòng phẳng." }
  ]
},
{
  id: "ngu-cuu-phao",
  name: "Ngũ Cửu Pháo vs Bình Phong Mã",
  cn: "五九炮对屏风马",
  side: "do", level: "Nâng cao",
  desc: "Từ trận Pháo đầu quen thuộc, Đỏ bình Pháo ra biên (lộ 9) mở cột cho Xe trái — hệ thống tấn công hai cánh tinh vi ở đẳng cấp cao.",
  idea: "Đỏ: Pháo 9 mở cột 8 cho Xe trái, hai Xe kẹp hai cánh Đen. Đen: đổi lại bằng Pháo 7 đuổi Xe và Mã ngoại phản kích.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [7,0,6,2], a: "Đen lên Mã." },
    { m: [7,9,6,7], a: "Lên Mã phải." },
    { m: [8,0,7,0], a: "Đen ra Xe." },
    { m: [8,9,7,9], a: "Xe trực." },
    { m: [1,0,2,2], a: "Bình Phong Mã hoàn chỉnh." },
    { m: [2,6,2,5], a: "Đẩy Tốt 7." },
    { m: [6,3,6,4], a: "Đen đối Tốt 7." },
    { m: [7,9,7,3], a: "Xe qua hà." },
    { m: [7,2,8,2], a: "Pháo bình biên chuẩn bị đuổi Xe." },
    { m: [7,3,6,3], a: "Xe áp cột 3." },
    { m: [8,2,8,1], a: "Pháo thoái một." },
    { m: [1,9,2,7], a: "Lên Mã trái." },
    { m: [3,0,4,1], a: "Đen lên Sĩ." },
    { m: [1,7,0,7], a: "Pháo bình 9! Nước định hình Ngũ Cửu Pháo — mở toang cột 8 cho Xe trái xuất trận." },
    { m: [0,0,1,0], a: "Đen ra Xe cột 2 đề phòng." },
    { m: [0,9,1,9], a: "Xe trái ra cột 8 — hai Xe Đỏ kẹp hai cánh, sức ép dâng cao." },
    { m: [8,1,6,1], a: "Pháo bình 7 đuổi Xe — Đen phản đòn đúng lúc." },
    { m: [6,3,5,3], a: "Xe né sang lộ 4, vẫn cắm sâu trong đất Đen." },
    { m: [6,2,7,4], a: "Mã nhảy ra ngoài hà — Mã ngoại hiếm thấy nhưng ở đây rất đắc địa: dọa xung kích cánh trái Đỏ. Trận đấu đỉnh cao bắt đầu!" }
  ]
},
{
  id: "thuan-phao-hoanh-xa",
  name: "Thuận Pháo Hoành Xa",
  cn: "顺炮横车",
  side: "do", level: "Trung cấp",
  desc: "Biến thể Thuận Pháo trong đó Đỏ chọn Xe hoành thay vì Xe trực — Xe dời sang lộ 6 đánh thọc vào sườn cung Tướng Đen.",
  idea: "Đỏ: Xe hoành sang lộ 6 phối hợp Mã Pháo công phá góc Sĩ Đen. Đen: Xe trực tiến sâu quấy phá, lấy công bù thủ.",
  moves: [
    { m: [7,7,4,7], a: "Pháo đầu." },
    { m: [7,2,4,2], a: "Đen thuận Pháo." },
    { m: [7,9,6,7], a: "Lên Mã giữ Pháo." },
    { m: [7,0,6,2], a: "Đen lên Mã." },
    { m: [8,9,8,8], a: "Xe hoành! Khác với Xe trực, Đỏ đưa Xe lên để dời ngang — hướng đi giàu tưởng tượng." },
    { m: [8,0,7,0], a: "Đen ra Xe trực." },
    { m: [8,8,3,8], a: "Xe bình 6 — chiếm lộ Sĩ, mũi dao kề sườn cung Tướng Đen." },
    { m: [7,0,7,6], a: "Xe Đen tiến sâu sát đáy — không chịu kém, lấy tấn công đáp trả tấn công." },
    { m: [1,9,2,7], a: "Lên Mã trái." },
    { m: [1,0,2,2], a: "Đen lên nốt Mã." },
    { m: [5,9,4,8], a: "Lên Sĩ — vừa củng cố vừa dọn đường cho Xe hoạt động ở lộ 6." },
    { m: [2,3,2,4], a: "Đen đẩy Tốt 3 mở đường Mã." },
    { m: [1,7,1,3], a: "Pháo 8 tiến 4 — phong tỏa tuyến Tốt, cắt liên lạc hai cánh của Đen." },
    { m: [3,0,4,1], a: "Đen lên Sĩ giữ cung." },
    { m: [0,9,1,9], a: "Xe trái ra chống lưng cho Pháo — toàn quân Đỏ đã vào vị trí chiến đấu." },
    { m: [0,0,1,0], a: "Xe phải Đen ra cột 2 đối mặt. Thuận Pháo Hoành Xa: một trong những thế trận đối công đẹp nhất của cờ Tướng!" }
  ]
}
];
if (typeof module !== "undefined") { module.exports = OPENINGS; }
